- name: Azure Arc-enabled Kubernetes
  href: index.yml
- name: Overview
  items:
  - name: About Azure Arc-enabled Kubernetes
    href: overview.md
  - name: What's new with Arc-enabled Kubernetes
    displayName: release, notes, version, latest
    href: release-notes.md
  - name: Azure Arc validated partners
    displayName: distributions, validation
    href: validation-program.md
- name: Quickstarts
  items:
  - name: Connect a cluster to Azure Arc
    displayName: enable, Arc-enable, deploy, quickstart
    href: quickstart-connect-cluster.md
- name: Tutorials
  items:
  - name: Deploy applications using GitOps (ArgoCD)
    displayName: argocd, tutorial
    href: tutorial-use-gitops-argocd.md
  - name: Deploy applications using GitOps (Flux v2)
    displayName: flux, tutorial, configuration
    href: tutorial-use-gitops-flux2.md
  - name: Implement CI/CD with GitOps (Flux v2)
    displayName: flux, pipeline
    href: tutorial-gitops-flux2-ci-cd.md
- name: Samples
  items:
  - name: Azure Resource Graph queries
    displayName: arg
    href: ./resource-graph-samples.md
- name: Concepts
  items:
  - name: Agent overview
    href: conceptual-agent-overview.md
  - name: System requirements
    displayName: memory, compute, prerequisites
    href: system-requirements.md
  - name: Network requirements
    displayName: endpoint, url, connection, connectivity, proxy
    href: network-requirements.md
  - name: Connectivity modes
    displayName: disconnected, semi-connected
    href: conceptual-connectivity-modes.md
  - name: Data exchange between cluster and Azure
    displayName: metadata
    href: conceptual-data-exchange.md
  - name: Identity and access management
    items:
      - name: Identity and access overview
        displayName: connect, rbac, authentication, authorization
        href: identity-access-overview.md
      - name: Cluster connect access
        displayName: identity
        href: conceptual-cluster-connect.md
      - name: Azure RBAC integration
        displayName: azure ad, azure active directory, identity, access, role
        href: conceptual-azure-rbac.md
      - name: Workload identity federation
        href: conceptual-workload-identity.md
  - name: Extend Azure capabilities to clusters anywhere
    items:
      - name: Cluster extensions
        href: conceptual-extensions.md
      - name: Available extensions
        displayName: gitops, flux, version
        href: extensions-release.md
      - name: Version-managed extensions
        href: managed-extensions.md
      - name: Custom locations
        displayName: target
        href: conceptual-custom-locations.md
  - name: Deploy applications to cluster
    items:
      - name: Application deployment with GitOps
        displayName: flux, deploy, configuration
        href: conceptual-gitops-flux2.md
      - name: GitOps (Flux v2) parameters
        href: gitops-flux2-parameters.md
      - name: CI/CD workflow using GitOps
        displayName: flux, pipeline
        href: conceptual-gitops-flux2-ci-cd.md
      - name: Multi-cluster workload management with GitOps
        displayName: multicluster
        href: conceptual-workload-management.md
      - name: Inner loop developer experience
        href: conceptual-inner-loop-gitops.md
      - name: GitOps with Flux v1
        items:
          - name: Configurations and GitOps (Flux v1)
            href: conceptual-configurations.md
          - name: Deploy configurations using GitOps (Flux v1)
            href: tutorial-use-gitops-connected-cluster.md
  - name: Security
    items:
    - name: Security baseline
      href: /security/benchmark/azure/baselines/azure-arc-enabled-kubernetes-security-baseline?toc=/azure/azure-arc/kubernetes/toc.json
  - name: Frequently Asked Questions
    displayName: FAQ
    href: faq.md
- name: How-to guides
  items:
  - name: Upgrade agents
    displayName: update, automatic
    href: agent-upgrade.md
  - name: Use Private Link Scope
    href: private-link.md
  - name: View resources in Azure portal
    displayName: workload
    href: kubernetes-resource-view.md
  - name: Deploy applications consistently
    displayName: GitOps, flux, configuration, policy, scale
    href: use-azure-policy-flux-2.md
  - name: Explore multi-cluster workload management
    displayName: gitops, application
    href: workload-management.md
  - name: Manage identity and access
    items:
    - name: Securely connect to cluster from anywhere
      displayName: cluster connect, authentication, access
      href: cluster-connect.md
    - name: Use Azure RBAC for authorization checks
      displayName: azure active directory, identity, access
      href: azure-rbac.md
    - name: Use workload identity
      href: workload-identity.md
  - name: Manage your cluster
    items:
    - name: Deploy and manage cluster extensions
      href: extensions.md
    - name: Deploy Azure Marketplace applications
      href: deploy-marketplace.md
    - name: Monitor using Azure Monitor Container Insights
      href: /azure/azure-monitor/containers/container-insights-enable-arc-enabled-clusters?toc=/azure/azure-arc/kubernetes/toc.json&bc=/azure/azure-arc/kubernetes/breadcrumb/toc.json
    - name: Monitor GitOps (Flux v2) activity
      displayName: dashboard, prometheus, compliance, status, reconciliation, activity
      href: monitor-gitops-flux-2.md
    - name: Enforce threat protection using Microsoft Defender for Cloud
      displayName: security
      href: /azure/defender-for-cloud/defender-for-kubernetes-azure-arc?toc=/azure/azure-arc/kubernetes/toc.json&bc=/azure/azure-arc/kubernetes/breadcrumb/toc.json
    - name: In-cluster policy enforcements using Azure Policy
      displayName: compliance
      href: /azure/governance/policy/concepts/policy-for-kubernetes?toc=/azure/azure-arc/kubernetes/toc.json&bc=/azure/azure-arc/kubernetes/breadcrumb/toc.json#install-azure-policy-extension-for-azure-arc-enabled-kubernetes
    - name: Deploy Azure Arc-enabled Open Service Mesh
      displayName: osm, microservice
      href: tutorial-arc-enabled-open-service-mesh.md
    - name: Access secrets from Azure Key Vault
      displayName: akv, cert
      href: tutorial-akv-secrets-provider.md
    - name: Access secrets offline from Azure Key Vault
      href: secret-store-extension.md
      displayName: secret synchronization, azure secret store, secret store
  - name: Deploy Arc-enabled services
    items:
      - name: Create custom locations
        displayName: target
        href: custom-locations.md
      - name: Azure Arc-enabled Machine Learning
        displayName: ML, AzureML, compute
        href: /azure/machine-learning/how-to-attach-kubernetes-anywhere?toc=/azure/azure-arc/kubernetes/toc.json&bc=/azure/azure-arc/kubernetes/breadcrumb/toc.json
  - name: Simplify network connectivity
    href: arc-gateway-simplify-networking.md
  - name: Troubleshooting
    items:
    - name: Platform issues
      displayName: problem, issue, resolve
      href: troubleshooting.md
    - name: Connection issues
      displayName: troubleshoot, problem, proxy, network
      href: diagnose-connection-issues.md
    - name: Extension issues
      displayName: gitops, flux, osm, open
      href: extensions-troubleshooting.md
- name: Reference
  items:
  - name: Azure Policy built-ins
    displayName: samples, policies, definitions
    href: policy-reference.md
  - name: Azure CLI
    href: /cli/azure/connectedk8s
  - name: Azure PowerShell
    href: /powershell/module/az.connectedkubernetes#connected-kubernetes
- name: Resources
  items:
  - name: Azure Arc Jumpstart
    href: https://aka.ms/AzureArcJumpstart
  - name: Microsoft Q&A for Azure Arc
    href: /answers/tags/146/azure-arc
  - name: Azure updates
    href: https://azure.microsoft.com/updates/
  - name: Pricing calculator
    href: https://azure.microsoft.com/pricing/calculator/
  - name: Regional availability
    href: https://azure.microsoft.com/explore/global-infrastructure/products-by-region/?products=azure-arc&regions=all
  - name: Product feedback
    href: https://feedback.azure.com/d365community/forum/5c778dec-0625-ec11-b6e6-000d3a4f0858